modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="tutorial_mod"
version="1.0.0"
displayName="Tutorial Mod"
authors="YourName"
description='''
A tutorial mod for Minecraft Forge 1.20.x demonstrating custom capability, HUD, entity, and network.
'''
[[dependencies.tutorial_mod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.tutorial_mod]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"